"use strict";

require("../src/index");

var base642Ab = function(base64) {
  var binary_string = window.atob(base64);
  var len = binary_string.length;
  var bytes = new Uint8Array(len);
  for (var i = 0; i < len; i++ ) {
    bytes[i] = binary_string.charCodeAt(i);
  }
  return bytes.buffer;
}

var pem = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ6VENDQTdXZ0F3SUJBZ0lJY2xNREZhbnZv"
+ "czR3RFFZSktvWklodmNOQVFFTEJRQXdhREVhTUJnR0ExVUUKQXd3UlVtOXZkQ0JEUVNCSmJtUnZi"
+ "bVZ6YVdFeFBUQTdCZ05WQkFvTU5FMXBibWx6ZEhKNUlHOW1JRU52YlcxMQpibWxqWVhScGIyNGdZ"
+ "VzVrSUVsdVptOXliV0YwYVc5dUlGUmxZMmh1YjJ4dloza3hDekFKQmdOVkJBWVRBa2xFCk1CNFhE"
+ "VEUwTVRJd01UQTJOVGMxTUZvWERUSXlNVEl3TVRBMk5UYzFNRm93WnpFWk1CY0dBMVVFQXd3UVNX"
+ "NTAKSUVOQklGQjFjbmRoY25Wd1lURTlNRHNHQTFVRUNndzBUV2x1YVhOMGNua2diMllnUTI5dGJY"
+ "VnVhV05oZEdsdgpiaUJoYm1RZ1NXNW1iM0p0WVhScGIyNGdWR1ZqYUc1dmJHOW5lVEVMTUFrR0Ex"
+ "VUVCaE1DU1VRd2dnSWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDQVFER1Vt"
+ "TWpvSG1reCsvMWNyTGxZM1UzNUl0bktpNWQKLzJjTVFZdGxydWlwY0VwT0lXQkZYblpFSFlUWE5m"
+ "ZE1SVk5raUZtL0dNK2o3NGgveU5Jb0NuSlNoU3ZHMkJhTwpPNjY5QkZNeEpoRE5FOTNIY212d3ZY"
+ "SDhLazI1cGFaTDU1SmxjVnRjR0Y3U1BMcFd5aGhWSitVL3pLUDBKd0RmClBHNXFwcER4aW5WelFR"
+ "Sm4zelFtZEZ6REhEdFlEQ3grTTcyKzVuVk51dCthZmUzQWR5L1p1TGdvYmpaNVlndXoKMmw3SnR5"
+ "YTgxWC9mSkVoakJUY2pzSE9PZ2JuVm5la3NCdGR2Vit6MVovbjhTWG9abld1RVNORTBRVEJKUmlF"
+ "eApOY1k0T2lOeE5raDY2RDdlNEN0RnNiNUs2UXNsK1Y3cG1wSVh5MTdNM1RiS0RCWGIzR2NkL1Ur"
+ "aWhUbmtyVzdHCmNTNHFQV001SjJEZVNTS0lZMkpFaHR0N1NOdnVmUGdjUlBhby91SDBLeUxwNTZY"
+ "RWFCTXNGQXY5NWU2b0VqTkMKNnVHY0k0NGRoUHdzeGNLQ2sxVExuQkxVWlkzVHdNRitoL1ZKanVQ"
+ "bUdrVkd4dFRUelB5Zm14aG1ocHdqZ21ZWApBclpyQXd6dFFvVzE3NEJicEkvK0tLK21QUkxJUHVQ"
+ "aXFsMGtxd3Q3ZGsvQzZtbEg0ckJMbFpyZkFjTzBOcStOCjg3VHpwRVlBaVlGeW9NbUVMZ2tzRnpo"
+ "M1VtT0xoU0ZWa3hBZlplU2h1YU51MTJwbFZxWFp5NnREbUYzSEJrMzUKa0dEVVM0OW5yaTVkM0J0"
+ "L0NhbW8xWnQxMEFUK001QkFVeVA0OWthYTNXc1h1Z1orQ0J4Q242djNxSDJ0R3VjdAo1R0R3VitQ"
+ "dzBqSERQd0lEQVFBQm8zd3dlakFkQmdOVkhRNEVGZ1FVVlBkaHBBL1A2c2lLV0N2WnFYeXdZOVMx"
+ "CkZDb3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWZCZ05WSFNNRUdEQVdnQlRUNVdjVU9FOEVwK2xv"
+ "bWVYakpzaTgKUkdDUTFUQVhCZ05WSFNBRUVEQU9NQXdHQ21DQ2FBRUJBUUVDQXdJd0RnWURWUjBQ"
+ "QVFIL0JBUURBZ0dHTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQjQ3OGtmcld0RXdIWDdHRTlM"
+ "K0pFR08xNFhyNVRaVjVuYnJRcGdGTko4Ck5XSUNUK2dvRU9WZE9NWGgyRm40ZUxLN3VyUVd5b2dr"
+ "VVA4bFZJNDZFczl3K0p1UHBaU1NrMUtEMTRZSXFvTloKVnVZT1libUt1L1d6RHNWOXlXY2tOT1B0"
+ "YlQ5NlZTRVZGSnEzSTY4SUFwWWRjcjZZUnloSWZYMjFZTzUrdTlZVwpwZEx6d3MxMkZ3S1MveWho"
+ "d1cwVUsvVDA3RTFLMmZJQmNCcmJiWUQ2N09PdVhZSmVOTVo0V1o5Q3hYNXNPbmVrCkRNMThlNm5R"
+ "cEMwY21Yc0JMTk9BWXhqNFU3M1hlNnpqUHB2blZiSlc4eVhTRGdSSzVNdFBsNjlnNzArWFVSYmkK"
+ "bnBnU09pd3docEdTcDE2blRYM2JZWjNUaGk3RFB6WkMyc2t2ejJFdHZiUDlOOVYxayt4RGV3YjdV"
+ "bVRLbllabwpXMVdWNE42R2Jha3B3WmN3MXZGMEFwTUVUaHhOVWVqc3NtUUVSbnlFcE9GUmhiYXNs"
+ "K2xKU3NDcFpsY2Y2Uy81Cnp1azZtSmkraHpRa3NHeHkwQm4zUGtUR1FhMVlMN29iOHZZdU4vNUZ0"
+ "aGVBdiszQUJvam5EM0tNVjB6Ym1wUjAKNlJjakYvaVlpWEN4VmRiMEhlQkFFR0Z2NnV0V3ZiYitp"
+ "TkNLTXpuWjRYN2tyMmd0RUoveGJ2OHFLSUxUc1l4LwpTdWxOZG1uWXVSVkZtRUNTMDF6SGtRM3NQ"
+ "Mlp6YXhoNGFaZmpYNG10TDdUUUpzbDZPMUF4K1oybVVxSGpRSzhXCmFKVklwanFPUy8xeHhaenJr"
+ "bzZVTUVtSlFlcEwxcHBJVEdUNXJQUVFpUG54R2FkNzJjY1ZkcUJvblVocm9XTHIKZ0E9PQotLS0t"
+ "LUVORCBDRVJUSUZJQ0FURS0tLS0tCg==";

var crl = "MIICZDCCAUwCAQEwDQYJKoZIhvcNAQELBQAwgccxCzAJBgNVBAYTAklEMRQwEgYDVQQIDAtES0kg"
+ "SmFrYXJ0YTEWMBQGA1UEBwwNSmFrYXJ0YSBQdXNhdDEqMCgGA1UECgwhQmFkYW4gT3Rvcml0YXMg"
+ "U2VydGlmaWthdCBEaWdpdGFsMSMwIQYDVQQLDBpVbml0IFBlbmVyYml0YW4gU2VydGlmaWthdDEW"
+ "MBQGA1UEAwwNc2VydGlmaWthdC5pZDEhMB8GCSqGSIb3DQEJARYSY2VydEBzZXJ0aWZpa2F0Lmlk"
+ "Fw0xNTA5MDYwOTU3MjBaFw0xNjA5MDUwOTU3MjBaMD8wEwICEAAXDTE1MDkwMzA1MzEwMFowEwIC"
+ "EAIXDTE1MDkwNjA5NTQxNlowEwICEAMXDTE1MDkwNjA5NTQ0OFqgDzANMAsGA1UdFAQEAgIQBjAN"
+ "BgkqhkiG9w0BAQsFAAOCAQEARKdZiCnA3FNj8sTxkq897k+6CNfeiD3zkM2niMVMFt1bcrDQF8DC"
+ "RIJlPfVfclm2btDIkwfY6nBHBM30x0LEANfmZ4OGDxT2vG+sn7xWUyAPspzyKViWHQu7zHg6dnUN"
+ "yWEMEmDTvMWd/wb0jpC7b9+f9KLkvK3+N7y/spAp/jrQDTSTfFmnUAH2Nahn02H3ZtjkZBDx5qjB"
+ "Bsosu7yVhraNVDqlMjTGFjdJIEsvwWJZRm/O+YVh7rxjw1ejJQrb4niuH/wPxA+sPEc/geYTRBDD"
+ "rx/h3ezJ5kbM+XepUk8EruwoiJgO/2JhH8Ah9VsF64z9XqX7KzgQBLsc5J3kKg==";

var p12 = "MIIJAwIBAzCCCMkGCSqGSIb3DQEHAaCCCLoEggi2MIIIsjCCAzQGCSqGSIb3DQEHAaCCAyUEggMhMIIDHTCCAxkGCyqGSIb3DQEMCgEDoIIC4TCCAt0GCiqGSIb3DQEJFgGgggLNBIICyTCCAsUwggKmoAMCAQICAQEwDQYJKoZIhvcNAQEFBQAwcDETMBEGA1UEAxMKYmxhbmtvbi5pbjELMAkGA1UEBhMCSUQxFDASBgNVBAgTC0phYm9kZXRhYmVrMRgwFgYDVQQHEw9SZXB1YmxpayBCb2pvbmcxDTALBgNVBAoTBFRlc3QxDTALBgNVBAsTBFRlc3QwHhcNMTUwOTA4MTMxNDUyWhcNMTYwOTA4MTMxNDUyWjBwMRMwEQYDVQQDEwpibGFua29uLmluMQswCQYDVQQGEwJJRDEUMBIGA1UECBMLSmFib2RldGFiZWsxGDAWBgNVBAcTD1JlcHVibGlrIEJvam9uZzENMAsGA1UEChMEVGVzdDENMAsGA1UECxMEVGVzdDCByjANBgkqhkiG9w0BAQEFAAOBuAAwgbQCgawAAAAABADWAAAAAAAAAAAAlQAKZwAFAAAAAAABAAAAAA0AAAAAAAUAAAAAAAAcAAAA7QAPAAAAAAAAAAAAAAAJAAAAAAAAAAPfAAgAAAAAAAAAAAwAAOsAAA3BAAAAAO4FAgAAAAAAAAAIAA4AAAAMAA0AAK4AAAACAAD4DAACAOsAAAAAAAMCCQAAAAD9DgAADwAAAAAqAgAAWwAGAAAPrgAAAAAAAAAAAAAMAgMACqujgbswgbgwDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMCAvQwOwYDVR0lBDQwMgYIKwYBBQUHAwEGCCsGAQUFBwMCBggrBgEFBQcDAwYIKwYBBQUHAwQGCCsGAQUFBwMIMBEGCWCGSAGG+EIBAQQEAwIA9zAsBgNVHREEJTAjhhtodHRwOi8vZXhhbXBsZS5vcmcvd2ViaWQjbWWHBH8AAAEwHQYDVR0OBBYEFIfVxGCZ63aQvEl6YGWTZl0LYlVAMA0GCSqGSIb3DQEBBQUAAwoAdW5kZWZpbmVkMSUwIwYJKoZIhvcNAQkVMRYEFMBALbD8WBk1Hq3wAGWMZWa00iyeMIIFdgYJKoZIhvcNAQcBoIIFZwSCBWMwggVfMIIFWwYLKoZIhvcNAQwKAQKgggUjMIIFHzBJBgkqhkiG9w0BBQ0wPDAbBgkqhkiG9w0BBQwwDgQIxeDGhVKohtMCAggAMB0GCWCGSAFlAwQBAgQQGU8oqsBnfwrmljPx5Rf65wSCBNDk17vod85HuMobslGDMIxnIe9HT3vjuHF+5oiVPNbHjh+JY+x/br0EtOOiZrTObdy6EOwlkOiEZwPdGh4KGiteSyhngQEGOdUXlDGiiqCCQh9GyDs/Rm77YHLI2ijLKI5Kl9SUA0vkIO9cHKvsG7k96JiGsWzyDbF5qNSy02N86pRfPiUnS/zisHleY3BHwYTCTfXcebkrBu78mK7X0jQ3OusooKushyXMFUJAu5DuQJSF1k/ohT5n4tOgDlbKeKkGu2ieU3URGtbcOcskm3/XfYzg/3yrme0agt8hVXiPiPsfQYG+gIcS2AdocAfnnxbc8XmByCB8yX+OANgDk9YYDyRRqzT2c2bfoGG/lJwxxXs5Asb2l7x8RkxZhRq1J9n6LtS6UxEZIM1tGI9/dcjMQHVcpxLx0ZNJ79+a9IHp5dwBHivBl5qjV2QPiVK5eGJmOfmkMIDwZDqXosjCMnHxVzhCm7PQYyzKaRkeEbjqkjmnlAIGcM2HM6vglaQHxqosNqXfLO1pPMGEDbD/3UgSNRAY062GyOXY7nJTqzeTJcLnnlYk/K41iSH+VlBC9HaiHXi5TUc9+jLZcf4umTO+yZP8PJzRLcEptIz+UGcYSBr4bSpN21D7aQyP4C2N4WvpY/lOZ030CzXnAOU4JyZ0Vzjm6+VFRUtZi8FZwxMmqFv4XrG4yBuqyY00lFScaGtlQUJSuYaoKi/idar7tOviqiS6oZ0Outd6X74TG3OxR0WcBnZy4u9YTVueyMfrieSYGU9t2NVlGF5Cn3gOOAhBmtOyWkaNqv6GZQ6YxXHdjOcvraKNLKXDJXUz6plVQfkN0mbgw6SG4Qu+zjIrRh3WZ9GP3xe3CJKSfyrsdi0yX7/bLy77dtvEezCiQUDiYqyO+byKn037i+go5uakd/xAArwkRq/u40KEKPsbh0OXP4AW1JotGvVCSmaEao8tlpSZoFUCqc6tqMkHXiG1cUZnz1B8CL/oNSnESXqpV0xbUa7Z1xC8AxVVpHhN8fPZIeiX7gH0b2sg7NWLoz2uw0I2VprVyjaNKQYDlvNXsDDYZsLsfQ2KuQ5zvD03nTLoABtRPyxjBfdAR5xKdjOFDb0ttQFPQn2DZKOtm7UvhXcRgy4/EPa0dz/Bmwg/r8fPpa+WmZnqypPYoiRaGrZFhfl3NQWTgkpYndRrAOjF3LaJny6R+CESHT4SryuhhNtjQN1fD9uiYEqJ841skWd9UxomERFJx7vQq5ImFsWXlxAjHvfyDG1kKtXM5s1MixL+AJXeWIoGsgH55SmdnpzVFfAIbJq80ukPclwazFE6GSlj96vlt/A2IGwY6oB6Y0FhzmPzuCcp2ejpup/kzqOHslk8U+W2KCDL7959WjXBY/uhkKjnUw9phDr0K9tLC6mca0+9rdSFNIlpyKsT0z2tX7FYiRynuBHJwWk1wXr1qP6sVIUm6AGb2JvE1CZiPRR8jn9CK3vb0a7zh+XZAI0aiwYORHtXcDJNmso048wgJMIST+pJHXfKTpILPMuuQiRzto9CViku1rAK5pkNXAK3+B2j8ol/7VPD3EOInjyYOoMCtnGNoRT0E9tnKP2E+w6zqnJRHxme/2W8437VAnd50DDrYpz95eolFLtVtcWW/a9ZqDElMCMGCSqGSIb3DQEJFTEWBBTAQC2w/FgZNR6t8ABljGVmtNIsnjAxMCEwCQYFKw4DAhoFAAQU4PFHQi1cz+XnsFgfc2Il4ytUeJgECNtj6euvgo3TAgIIAA==";

var PSrEKominfo = "U3ViamVjdDogQ049UFNyRSBLb21pbmZvLE89S2VtZW50ZXJpYW4gS29tdW5pa2FzaSBkYW4gSW5m"
+ "b3JtYXRpa2EsQz1JRApJc3N1ZXI6IENOPUludCBDQSBQdXJ3YXJ1cGEsTz1NaW5pc3RyeSBvZiBD"
+ "b21tdW5pY2F0aW9uIGFuZCBJbmZvcm1hdGlvbiBUZWNobm9sb2d5LEM9SUQKLS0tLS1CRUdJTiBD"
+ "RVJUSUZJQ0FURS0tLS0tCk1JSUdjRENDQkZpZ0F3SUJBZ0lJR2UrZlJwL3ZzbWN3RFFZSktvWklo"
+ "dmNOQVFFTEJRQXdaekVaTUJjR0ExVUUKQXd3UVNXNTBJRU5CSUZCMWNuZGhjblZ3WVRFOU1Ec0dB"
+ "MVVFQ2d3MFRXbHVhWE4wY25rZ2IyWWdRMjl0YlhWdQphV05oZEdsdmJpQmhibVFnU1c1bWIzSnRZ"
+ "WFJwYjI0Z1ZHVmphRzV2Ykc5bmVURUxNQWtHQTFVRUJoTUNTVVF3CkhoY05NVFF4TWpBeE1EY3hO"
+ "akF5V2hjTk1Ua3hNakF4TURjeE5qQXlXakJWTVJVd0V3WURWUVFEREF4UVUzSkYKSUV0dmJXbHVa"
+ "bTh4THpBdEJnTlZCQW9NSmt0bGJXVnVkR1Z5YVdGdUlFdHZiWFZ1YVd0aGMya2daR0Z1SUVsdQpa"
+ "bTl5YldGMGFXdGhNUXN3Q1FZRFZRUUdFd0pKUkRDQ0FpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdn"
+ "SVBBRENDCkFnb0NnZ0lCQUsvd25SVXFhMTB0YzIxdU91dG1SZXBUMCtuMks2S0ZCTHJnSTNTa24r"
+ "WXFQUWU0dzNKMzFaVWQKZS94Uk9XamVQYlRUQWJSZFJBdCtxMkMyV2MrYVFLUzZzZjRVRTQ1UENW"
+ "TkM0Ly9KOUVRRXE0L0JDNk12RktkSgo5Q0M5QWRCSGhMZTV0UG5DOStLanBrTkUycFExZS9STTN0"
+ "UG15VVNtZTBjb2N0MnNkcmRWTnZNODhlUEhhbllSCno0VDJhZVNtekhBblJxTnhDN2F0RDRhTHAy"
+ "dXIzVnRJemcvczFBNlZIRmRHMW9sWGQyQzYyWjdPbGliQXhNMWMKd3dZcWRaOW90RllLZmk0ZzYv"
+ "T3pOaUVRUjlFNk14clR1NGZYWFJYRGVSbVB5Vko5clNOc0JGWGhNT0t2dWxBQgpkdjVEc2JTVUQ2"
+ "MFh3c2RWbTNuVHR1ZkRVZXIwM2hLdUo4bWsyR3pLNFhYdHlzaVhLd0g1VjZzVFRaYjlYM3JtCmJ5"
+ "SGMrWEk5U2VLRWZ6TnJEMlJYZCtacnlDNWtrS3M1bjJ1RlJxbnBkUWJ4QkZKdVRVVU4yUmIzRjFY"
+ "NXlHKzgKTGdzQUxuWFNmZzhMMllKMW15SDJwMEhBbGZ2RzVPamlyczVnL2YyR3FjeWc0YlNla0c2"
+ "TEl4OWFxRm1GN05uRwpBY3E4cEFvSVJLbHJaSlhSaXZtUU9PRzMwU2c0R3RlZlVGYVIvS0xLYkZj"
+ "U0w0SFVTQU5oUk5acFBicllycWZVCm55SWQyZ3ovTmduRXd0cUlqM2UraFNicW9oSGhkUWxmdjkx"
+ "eTM5WExmZUlQa0tVQ0t1TWErNjZ5MkNvcjhGRXAKaGdKVVVxK3NXbXJSQWJUNHF3VlFTV1dlbFdx"
+ "bHp0ZjRnbVUyRXEzbjV0Z0VyK2x0M0tlWEFnTUJBQUdqZ2dFdwpNSUlCTERBZEJnTlZIUTRFRmdR"
+ "VWZlTklDTzZsTTZ2WXJ5U2FoZWNFRHlsY2ZpTXdEd1lEVlIwVEFRSC9CQVV3CkF3RUIvekFmQmdO"
+ "VkhTTUVHREFXZ0JSVTkyR2tEOC9xeUlwWUs5bXBmTEJqMUxVVUtqQVpCZ05WSFNBRUVqQVEKTUE0"
+ "R0RHQ0NhQUVCQVFFQkFnTUVBakNCclFZRFZSMGZCSUdsTUlHaU1JR2ZvRENnTG9Zc2FIUjBjRG92"
+ "TDNkMwpkeTV5YjI5MFkyRXViM0l1YVdRdlkzSnNMM0J6Y21WcGJuUndkWEozWVM1amNteWlhNlJw"
+ "TUdjeEdUQVhCZ05WCkJBTU1FRWx1ZENCRFFTQlFkWEozWVhKMWNHRXhQVEE3QmdOVkJBb01ORTFw"
+ "Ym1semRISjVJRzltSUVOdmJXMTEKYm1sallYUnBiMjRnWVc1a0lFbHVabTl5YldGMGFXOXVJRlJs"
+ "WTJodWIyeHZaM2t4Q3pBSkJnTlZCQVlUQWtsRQpNQTRHQTFVZER3RUIvd1FFQXdJQmhqQU5CZ2tx"
+ "aGtpRzl3MEJBUXNGQUFPQ0FnRUFRTlpxRUJJTHdOWkxKbC9NClQ0ZkdBQy9BRXo5ZGZqT24xaHdO"
+ "T3Z2L3dBMHVaRmpMUTQraHYyT1E1M2xjM1lxbmpWdkkzbDBycW01T3BVRm4KTmpFQlRnd0VZT1N1"
+ "NTRLSHVELzhldmlwOW9hZ0RWcE1MWUYzam5wWTNOUXowWE12ZGJTUW1TR0dkakg2NjNjUgorajly"
+ "MWxsMW55c2lZNEg2OWhQa09jOElsNXBta2VXQ0xHem9TZUcwRy9mUEovUHVwM0RIMmg5ZCsyaHZx"
+ "YTI2ClBOSDFzTTczTVF1YTJhVlBDUWhJa0hTOU5oeVJiT1ZRLzVYQk1PaUd2QTM2SEVST3dpSTVu"
+ "OExqVkF0MThyZnMKT2QyWnpmOG8za1c1dWlEVjY2cm9nV1g0c3lzcFBNTTFyYWdma2dtRkRDN2xr"
+ "eHF4cGhSZ1RsQ2hhaFFlMXhXUQpOVXRoVUt6bXZxY0pMNDJnME5tei9IQmc3TXNVd2J1UXdmbzJC"
+ "UlRWWEVjK1Rwdkk3QnpZNlNuRktkRCtjS1RUCmw0NVZrNlkzb2dKKzRBUGp5TjFCTzk3YXZOeTds"
+ "QVlCditCTEJiT29CdElraHhhTGhxRTI3V2JhaGZ2aG9xUWgKNVlPYlk3K1VWRUNCZjJqUlErdnNz"
+ "aVRnbzB4V1BMbE9CN1hWUlZKWm9MQmtnRytHMFZjdVNNeE90UEdPMkM1NQpVLzBEVDBPSjd1bXYr"
+ "d3Q0ajJIZCtIMU9TdHFBL0lLTVg2NkZDSnNIdC9la09Yak00VUpzeTFWNXg4Tkw4U2wyCklNNnc3"
+ "V3o4RjhhdFRweENhOUZ1RVVkaUtGR1VHU0VianpzbFlJc29GNS9ueE9aNjhqMzV1RUI4eERyTDM1"
+ "K1QKYTA2dDlGLzZQSVZ1TVNHVnRjMTYyMkkxY1VJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
+ "ClN1YmplY3Q6IENOPUludCBDQSBQdXJ3YXJ1cGEsTz1NaW5pc3RyeSBvZiBDb21tdW5pY2F0aW9u"
+ "IGFuZCBJbmZvcm1hdGlvbiBUZWNobm9sb2d5LEM9SUQKSXNzdWVyOiBDTj1Sb290IENBIEluZG9u"
+ "ZXNpYSxPPU1pbmlzdHJ5IG9mIENvbW11bmljYXRpb24gYW5kIEluZm9ybWF0aW9uIFRlY2hub2xv"
+ "Z3ksQz1JRAotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRnpUQ0NBN1dnQXdJQkFnSUlj"
+ "bE1ERmFudm9zNHdEUVlKS29aSWh2Y05BUUVMQlFBd2FERWFNQmdHQTFVRQpBd3dSVW05dmRDQkRR"
+ "U0JKYm1SdmJtVnphV0V4UFRBN0JnTlZCQW9NTkUxcGJtbHpkSEo1SUc5bUlFTnZiVzExCmJtbGpZ"
+ "WFJwYjI0Z1lXNWtJRWx1Wm05eWJXRjBhVzl1SUZSbFkyaHViMnh2WjNreEN6QUpCZ05WQkFZVEFr"
+ "bEUKTUI0WERURTBNVEl3TVRBMk5UYzFNRm9YRFRJeU1USXdNVEEyTlRjMU1Gb3daekVaTUJjR0Ex"
+ "VUVBd3dRU1c1MApJRU5CSUZCMWNuZGhjblZ3WVRFOU1Ec0dBMVVFQ2d3MFRXbHVhWE4wY25rZ2Iy"
+ "WWdRMjl0YlhWdWFXTmhkR2x2CmJpQmhibVFnU1c1bWIzSnRZWFJwYjI0Z1ZHVmphRzV2Ykc5bmVU"
+ "RUxNQWtHQTFVRUJoTUNTVVF3Z2dJaU1BMEcKQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0Fv"
+ "SUNBUURHVW1Nam9IbWt4Ky8xY3JMbFkzVTM1SXRuS2k1ZAovMmNNUVl0bHJ1aXBjRXBPSVdCRlhu"
+ "WkVIWVRYTmZkTVJWTmtpRm0vR00rajc0aC95TklvQ25KU2hTdkcyQmFPCk82NjlCRk14SmhETkU5"
+ "M0hjbXZ3dlhIOEtrMjVwYVpMNTVKbGNWdGNHRjdTUExwV3loaFZKK1UvektQMEp3RGYKUEc1cXBw"
+ "RHhpblZ6UVFKbjN6UW1kRnpESER0WURDeCtNNzIrNW5WTnV0K2FmZTNBZHkvWnVMZ29ialo1WWd1"
+ "egoybDdKdHlhODFYL2ZKRWhqQlRjanNIT09nYm5WbmVrc0J0ZHZWK3oxWi9uOFNYb1puV3VFU05F"
+ "MFFUQkpSaUV4Ck5jWTRPaU54TmtoNjZEN2U0Q3RGc2I1SzZRc2wrVjdwbXBJWHkxN00zVGJLREJY"
+ "YjNHY2QvVStpaFRua3JXN0cKY1M0cVBXTTVKMkRlU1NLSVkySkVodHQ3U052dWZQZ2NSUGFvL3VI"
+ "MEt5THA1NlhFYUJNc0ZBdjk1ZTZvRWpOQwo2dUdjSTQ0ZGhQd3N4Y0tDazFUTG5CTFVaWTNUd01G"
+ "K2gvVkpqdVBtR2tWR3h0VFR6UHlmbXhobWhwd2pnbVlYCkFyWnJBd3p0UW9XMTc0QmJwSS8rS0sr"
+ "bVBSTElQdVBpcWwwa3F3dDdkay9DNm1sSDRyQkxsWnJmQWNPME5xK04KODdUenBFWUFpWUZ5b01t"
+ "RUxna3NGemgzVW1PTGhTRlZreEFmWmVTaHVhTnUxMnBsVnFYWnk2dERtRjNIQmszNQprR0RVUzQ5"
+ "bnJpNWQzQnQvQ2FtbzFadDEwQVQrTTVCQVV5UDQ5a2FhM1dzWHVnWitDQnhDbjZ2M3FIMnRHdWN0"
+ "CjVHRHdWK1B3MGpIRFB3SURBUUFCbzN3d2VqQWRCZ05WSFE0RUZnUVVWUGRocEEvUDZzaUtXQ3Za"
+ "cVh5d1k5UzEKRkNvd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZkJnTlZIU01FR0RBV2dCVFQ1V2NV"
+ "T0U4RXArbG9tZVhqSnNpOApSR0NRMVRBWEJnTlZIU0FFRURBT01Bd0dDbUNDYUFFQkFRRUNBd0l3"
+ "RGdZRFZSMFBBUUgvQkFRREFnR0dNQTBHCkNTcUdTSWIzRFFFQkN3VUFBNElDQVFCNDc4a2ZyV3RF"
+ "d0hYN0dFOUwrSkVHTzE0WHI1VFpWNW5iclFwZ0ZOSjgKTldJQ1QrZ29FT1ZkT01YaDJGbjRlTEs3"
+ "dXJRV3lvZ2tVUDhsVkk0NkVzOXcrSnVQcFpTU2sxS0QxNFlJcW9OWgpWdVlPWWJtS3UvV3pEc1Y5"
+ "eVdja05PUHRiVDk2VlNFVkZKcTNJNjhJQXBZZGNyNllSeWhJZlgyMVlPNSt1OVlXCnBkTHp3czEy"
+ "RndLUy95aGh3VzBVSy9UMDdFMUsyZklCY0JyYmJZRDY3T091WFlKZU5NWjRXWjlDeFg1c09uZWsK"
+ "RE0xOGU2blFwQzBjbVhzQkxOT0FZeGo0VTczWGU2empQcHZuVmJKVzh5WFNEZ1JLNU10UGw2OWc3"
+ "MCtYVVJiaQpucGdTT2l3d2hwR1NwMTZuVFgzYllaM1RoaTdEUHpaQzJza3Z6MkV0dmJQOU45VjFr"
+ "K3hEZXdiN1VtVEtuWVpvClcxV1Y0TjZHYmFrcHdaY3cxdkYwQXBNRVRoeE5VZWpzc21RRVJueUVw"
+ "T0ZSaGJhc2wrbEpTc0NwWmxjZjZTLzUKenVrNm1KaStoelFrc0d4eTBCbjNQa1RHUWExWUw3b2I4"
+ "dll1Ti81RnRoZUF2KzNBQm9qbkQzS01WMHpibXBSMAo2UmNqRi9pWWlYQ3hWZGIwSGVCQUVHRnY2"
+ "dXRXdmJiK2lOQ0tNem5aNFg3a3IyZ3RFSi94YnY4cUtJTFRzWXgvClN1bE5kbW5ZdVJWRm1FQ1Mw"
+ "MXpIa1Ezc1AyWnpheGg0YVpmalg0bXRMN1RRSnNsNk8xQXgrWjJtVXFIalFLOFcKYUpWSXBqcU9T"
+ "LzF4eFp6cmtvNlVNRW1KUWVwTDFwcElUR1Q1clBRUWlQbnhHYWQ3MmNjVmRxQm9uVWhyb1dMcgpn"
+ "QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KU3ViamVjdDogQ049Um9vdCBDQSBJbmRvbmVz"
+ "aWEsTz1NaW5pc3RyeSBvZiBDb21tdW5pY2F0aW9uIGFuZCBJbmZvcm1hdGlvbiBUZWNobm9sb2d5"
+ "LEM9SUQKSXNzdWVyOiBDTj1Sb290IENBIEluZG9uZXNpYSxPPU1pbmlzdHJ5IG9mIENvbW11bmlj"
+ "YXRpb24gYW5kIEluZm9ybWF0aW9uIFRlY2hub2xvZ3ksQz1JRAotLS0tLUJFR0lOIENFUlRJRklD"
+ "QVRFLS0tLS0KTUlJR0NUQ0NBL0dnQXdJQkFnSUlDaTZnWWZ0QjdtOHdEUVlKS29aSWh2Y05BUUVM"
+ "QlFBd2FERWFNQmdHQTFVRQpBd3dSVW05dmRDQkRRU0JKYm1SdmJtVnphV0V4UFRBN0JnTlZCQW9N"
+ "TkUxcGJtbHpkSEo1SUc5bUlFTnZiVzExCmJtbGpZWFJwYjI0Z1lXNWtJRWx1Wm05eWJXRjBhVzl1"
+ "SUZSbFkyaHViMnh2WjNreEN6QUpCZ05WQkFZVEFrbEUKTUI0WERURTBNVEV4TURBek5EZzFNbG9Y"
+ "RFRJME1URXhNREF6TkRnMU1sb3dhREVhTUJnR0ExVUVBd3dSVW05dgpkQ0JEUVNCSmJtUnZibVZ6"
+ "YVdFeFBUQTdCZ05WQkFvTU5FMXBibWx6ZEhKNUlHOW1JRU52YlcxMWJtbGpZWFJwCmIyNGdZVzVr"
+ "SUVsdVptOXliV0YwYVc5dUlGUmxZMmh1YjJ4dloza3hDekFKQmdOVkJBWVRBa2xFTUlJQ0lqQU4K"
+ "QmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBdGhIa1FJSENLNUlNVEpHc1V1bXVZ"
+ "SXgrWDhxbgp1R2xVU0hjdkw0cVV2SXM3cHcvYS95c2pOTzFzV042U1ozRXJ5c1pXV0RVVjc5bEp6"
+ "eXpybWhQeHBDOHpYc2NICktWRHNpSnhqUUFoUWhKS2c0Snk0QkN5L3pNWnVodDZMQ3JEaVJ5djcv"
+ "Y3RhRkZ0M1JwVGNGM1Z6ekxzTGo3MnoKbkpVaXI0T3hZWE1IVHU0WEF6R0FYcnREZW4xVXZYQ1Vk"
+ "b2tuV2RYTk41blJhL1hKdU5FV2VQc08rMkVCbUhvUQpqV3U2L2Yvc1R0ZzMzNWZmV2dwNnFYdG8r"
+ "aTFkYU45dmVWMFZLbWRoMWQ2cVhRT1ZwaTBkaEJsUU15eDlPdVM1Ckk2bUV4NHY5L0I3WE9RMnVL"
+ "aUJac0NaM0xoQjVEY3RhUVZNQ3RRYlU4Yjl1RUx4QmVMdy85bEhsalo2M29Ed2UKRGhXblBVNDFG"
+ "cmJSQ3pOTTFCMFIrdzROWWowU082V3B4T0FuNkF1cFl5S2g0dlNqdEx5TWVhRndGcDl2WXlWMQpx"
+ "Vk5aRG11RWZETzBhdG8wdzVrQVY1TGNDZ0k0RXp0NTVyQi9IQ29TMWo2eDAweFJOWEc4akpzMkIv"
+ "YWlKWmJqCmNNZ0ZkSVREbkRkNFpHdGFtUmhxZlVuWE9DYVN4YW1TbExJUFcvVkFVSGtvYy9pbGxk"
+ "bGZzZlZTMFAwVjVINWMKY2FxTUdCSTBQYnlVMThWdmlxSWFZdjNQT1pRK0ZweFdnN2ovWTJJOE9s"
+ "TnBSWVovNzRRWG9rMmZiSE80T2tJdwptUEh4bHQ0RW5DcU1ZVEFBcjlMZnZJL2tJMVFndHczNWtu"
+ "OGtsbFZVN2xHeThqQTlxcXdXNVRDbG5iWTBhWmRPCkRndkJFcjFZZm0ya3Bja0NBd0VBQWFPQnRq"
+ "Q0JzekFkQmdOVkhRNEVGZ1FVMCtWbkZEaFBCS2ZwYUpubDR5YkkKdkVSZ2tOVXdEd1lEVlIwVEFR"
+ "SC9CQVV3QXdFQi96QWZCZ05WSFNNRUdEQVdnQlRUNVdjVU9FOEVwK2xvbWVYagpKc2k4UkdDUTFU"
+ "QlFCZ05WSFNBRVNUQkhNRVVHQ0dDQ2FBRUJBUUVCTURrd053WUlLd1lCQlFVSEFnRVdLMmgwCmRI"
+ "QTZMeTh2ZDNkM0xuSnZiM1JqWVM1dmNpNXBaQzlEVUM5d2MzSmxTVzVrZFd0amNDNXdaR1l3RGdZ"
+ "RFZSMFAKQVFIL0JBUURBZ0dHTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFCQkJMelFoUC9OYVI3"
+ "L1MxanZtLzNzdHFXegpOUExvYmJhaFExTHJEMmpRV3BlbWxuZmxoZjI1UkF2LzVFRDIydSt3MEY0"
+ "TTlVOTJSbUhsTTNjSnJKeURIRXVpCjZFQUlGbUErTVVlQ280d1JHZzVLSHg4eklXampvMk8xVk4r"
+ "UXlmT3NCVWRueWNQb2pUTnNML1kxdFBsOGI5WWoKWElsOUVLOVVvNXg1VTZwbVdHUVNnemhUblk5"
+ "aWkwczJTWVFjSlNvVDAvU2xUVkwrL25UOWsvWEs1Vm1CY3BJcwp4eGVMOHlPM3V1OXIxdXd6Qmdn"
+ "UlYrOUhEODllcjdvcUMzbSt4UW84NitpenBpUFlNbmVWQzhSMVVrci9oM3pDCmkzRzVwVUlFNFRN"
+ "cmRQZTNqTDdjNVZlQS85N05VVzhnWkpQbFA4eWo5RlErMlNQZzNkZEoxdFB0cG4yS2lyVncKWFBl"
+ "emZCNmNHb1pBSVJkNmFQaFhac09ZdXVZOU1KTURWRXBob0VCeTVlOUM3dXk5cy92ZWtaODdxU1NT"
+ "KzlzNQp4QzQwNHowWVh2RTlXWThBcitQejBqUjFaTDM0M0RsZ2ZXR21pUFZvbFdveVFRc21raFhV"
+ "QkYxZk1kWXJpT1RRCkdpaXVESnZoMytic1lLd2RpaG56Rk43NGVlTytRZHErZXdhY2ZKYVNVd3dW"
+ "NXlTNWwxU0ZlbWpNbnMyYjhzd3kKYmFucTdEZ2NNUmc2UGF1RGI0bkhtN3pUbXJ1RXIwMmZNdUx3"
+ "K3V6U1RvZUhXZDlMV3g0dG1oaE9KNmxZTzNCMgpYVzJlYllQRHRZR1ZvWXYxUXliWm1jQ0U5ZHdo"
+ "MkhkdTBHTEQ5ZllCNy9EQVYwcnNLRWRXWWJmK3hOcnE2bmdvCm1LSTN0cHZKdGxMTWR1VzBKQT09"
+ "Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K";

var UI = require("../src/ui");
describe("UI Class", function() {
  describe("Render Element", function() {
    it("Render element to get certificate PEM", function(done) {
      document.body.innerHTML += "<div id='parse-pem'></div>";
      var file = new File([base642Ab(pem)], "pem.txt", {lastModified : new Date(0), type: "text/plain"})
      UI.getCertPEM("parse-pem", function(promise){
        // Do nothing
      })
      UI.handler.PEM(file)
        .then(function(cert){
          console.log(cert);
          expect(cert.certData.length).toBe(1);
          cert.getSubject()
            .then(function(subject){
              expect(subject.commonName).toBe("Int CA Purwarupa");
              done();
            })
            .catch(function(err){
              console.log(err.message);
              expect(1).toBe(2);
              done();
            })
        })
        .catch(function(err){
          console.log(err.message);
          expect(1).toBe(2);
          done();
        })
    });
    it("Render element to get CRL", function(done) {
      document.body.innerHTML += "<div id='parse-crl'></div>";
      var file = new File([base642Ab(crl)], "crl.crl", {lastModified : new Date(0), type: "text/plain"})
      UI.getCRL("parse-pem", function(promise){
        // Do nothing
      })
      UI.handler.CRL(file)
        .then(function(revocationList){
          console.log(revocationList);
          expect(revocationList.length).toBe(3);
          expect(revocationList[0]).toBe("1000");
          expect(revocationList[1]).toBe("1002");
          expect(revocationList[2]).toBe("1003");
          done();
        })
        .catch(function(err){
          console.log(err.message);
          expect(1).toBe(2);
          done();
        })
    });
    it("Render element to get P12", function(done) {
      document.body.innerHTML += "<div id='parse-p12'></div>";
      UI.getP12("parse-p12", function(promise){
        // Do nothing
      })
      document.getElementById("pkiwebsdk-p12-password").value = "password";
      var file = new File([base642Ab(p12)], "cert.p12", {lastModified : new Date(0), type: "application/x-pkcs12"})
      UI.handler.P12(file)
        .then(function(result){
          result.certificate.getSubject()
            .then(function(subject){
              expect(subject.commonName).toBe("blankon.in");
              expect(result.privateKey.substr(0,31)).toBe("-----BEGIN RSA PRIVATE KEY-----");
              done();
            })
            .catch(function(err){
              console.log(err.message);
              expect(1).toBe(2);
              done();
            })
        })
        .catch(function(err){
          console.log(err.message);
          expect(1).toBe(2);
          done();
        })
    });
    it("Render element to get Certificate Chain", function(done) {
      document.body.innerHTML += "<div id='parse-cert-chain'></div>";
      UI.certChain = new window.PKIWebSDK.Certificate();
      UI.getCertChain("parse-cert-chain", function(promise){
        // Do nothing
      })
      var file = new File([base642Ab(PSrEKominfo)], "cert.p12", {lastModified : new Date(0), type: "application/x-pkcs12"})
      UI.handler.certChain(file);
      setTimeout(function(){
        document.getElementById("pkiwebsdk-get-cert-chain-validate").click();
        expect(UI.certChain.certData.length).toBe(1);
        UI.certChain.validate()
          .then(function(isValid){
            expect(isValid).toBe(true);
            done();
          })
      }, 1000);
    });
  });
});
